### PR TITLE
Documentation clarification and startActivity DSL fix

### PR DESCRIPTION
**Pull request by dexafree**
* Adds a clarification for the `SwissKnife.inject(this, getView())` in Fragments
* Fixes a bug that would crash if `startActivity(Class)` was called with a null Closure

### CODE REVIEW

**Comment by eugene-kamenev** [comment]
looks ok, lets merge this pull request?

**Comment by Arasthel** [comment]
Yes, let's do it. We really have to improve some of the DSL methods, as come have parameters that should be optionals, while they really aren't.

**Comment by eugene-kamenev** [comment]
@Arasthel you can just point me to these methods, no problem to rewrite. I will search for all closure params, if they can be optional i will do.  Thanks.

**Comment by Arasthel** [comment]
By what I have seen, I think most of the DSL methods written by Cedric work that way. They always expect a closure and crash when they don't.

**Comment by eugene-kamenev** [comment]
@Arasthel fixed in new branch, take a look. Thanks.

**Pull request merged**
