### PR TITLE
Created 10 new res-injecting annotations and transformator for them.

### PR DESCRIPTION
**Pull request by MrBIMC**
new Annotations:
(String) @StringRes,
(Integer,int) @IntegerRes,
(Boolean,boolean) @BooleanRes,
(Float,float) @DimenRes,
(Integer,int) @ColorRes,
(String[]) @StringArrayRes,
(int[]) @IntegerArrayRes,
(Drawable) @DrawableRes,
(Animation) @AnimationRes,
(ColorStateList) @ColorStateListRes

Each annotation optionally applies single param(link to resource like R.sting.app_name, R.dimen.awesomeness_level), if annotation is applied without param, transformer will try to access resource by the name of variable.

For now supported only resources from in-app package(i.e. R.*), android.R.* resources will not work.

### CODE REVIEW

**Comment by eugene-kamenev** [comment]
Hey, big thanks for contributing, I think PR looks nice. Can't build it
right now.

As a humor: SwissKnife should define TooManyAnnotationsException :D
21 мая 2015 г. 20:39 пользователь "Pavel" <notifications@github.com>
написал:
>
> new Annotations:
> (String) @StringRes,
> (Integer,int) @IntegerRes,
> (Boolean,boolean) @BooleanRes,
> (Float,float) @DimenRes,
> (Integer,int) @ColorRes,
> (String[]) @StringArrayRes,
> (int[]) @IntegerArrayRes,
> (Drawable) @DrawableRes,
> (Animation) @AnimationRes,
> (ColorStateList) @ColorStateListRes
>
> Each annotation optionally applies single param(link to resource like
R.sting.app_name, R.dimen.awesomeness_level), if annotation is applied
without param, transformer will try to access resource by the name of
variable.
>
> For now supported only resources from in-app package(i.e. R.), android.R.
resources will not work.
>
> ________________________________
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Arasthel/SwissKnife/pull/27
>
> Commit Summary
> Created 10 new res-injecting annotations and transformator for them.
> File Changes
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/AnimationRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/BooleanRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/ColorRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/ColorStateListRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/DimenRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/DrawableRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/IntegerArrayRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/IntegerRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/ResTransformation.groovy
(102)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/StringArrayRes.groovy
(18)
> A
SwissKnife/src/main/groovy/com/arasthel/swissknife/annotations/resources/StringRes.groovy
(18)
> M SwissKnife/src/main/groovy/com/arasthel/swissknife/utils/Finder.groovy
(167)

**Comment by MrBIMC** [comment]
When will you accept this?

Cuz I'd like to use SwissKnife through **compile "com.arasthel:swissknife:+"** rather than importing my local module.

**Comment by Arasthel** [comment]
I was doing some testing and I found that this:

```groovy
@IntegerArrayRes(R.array.int_array)
    Integer[] intArray
```

Will throw this error `General error during canonicalization: Annotated field must be int[]. Type: [Ljava.lang.Integer;`. I don't know if you only wanted to support int[] or if this is a bug. I'll keep testing a bit.

**Comment by Arasthel** [comment]
There are a couple of bugs, actually:

```groovy
@AnimationRes(R.anim.abc_fade_in)
    Animation anim ````

Throws: `com.arasthel.swissknife.annotations.resources.ResTransformation$WrongTypeException: Annotated field must be Animation. Type: android.view.animation.Animation`.

While looking at that, I found some typos on ResTransformation, I have commented them on your commit. I think that with those fixed everything should be fine. Thanks and sorry for taking so long to reply, I've been quite busy lately.

**Comment by MrBIMC** [comment]
Oh, ok. Sorry for my derps with Animation in int[] typing :D

**Comment by MrBIMC** [comment]
Ok, let's cancel this one, I'll create new pull request with fixes in a minute.

**Pull request closed without merging**
