### PR TITLE
Added inject(Object, Activity) method

### PR DESCRIPTION
**Pull request by OrdonTeam**
Hi,
Since I was using SwissKnife outside an activity class, I had to make ugly hack to get to a view. Adding this method solved my problem.

### CODE REVIEW

**Comment by eugene-kamenev** [comment]
Hi, can you please provide more information, what you did, and what problem you experienced?

**Comment by OrdonTeam** [comment]
Oh, I was something so simple like this:
```
@CompileStatic
class Controller {//Not an activity nor view
    @InjectView(R.id.myId)
    View view
    Controller(Activity activity) {
        //Ugly hack to get view from activity
        SwissKnife.inject(this, activity.getWindow().getDecorView())
        //This is much prettier
        SwissKnife.inject(this, activity)
    }
}
```
I might used improper words in description, sorry.

**Comment by eugene-kamenev** [comment]
OK i see now, I think @Arasthel should take a look at it.
But, by the way, did you took a look at Swissknife DSL packages? I provides interesting things.
~~~
@CompileStatic
class Controller {//Not an activity nor view
    View view
    
    Controller(Activity activity) {
         this.view = activity.window.decorView.view(R.id.myId)
    }
}
~~~

**Comment by Arasthel** [comment]
I see the problem, I hadn't really thought about this scenario, and yes, passing the decorview of the Activity is a really ugly way to access its views. Thanks for the PR :+1:

**Pull request merged**
